<?php

if (!isset($this->vars()->obj)) {
	echo "No object model passed";
} else if(is_array($this->obj)) {
	if (isset($this->obj['message'])) {
		echo $this->obj['message'];
	}
	if (isset($this->obj['helper']) && isset($this->obj['data'])) {
		echo $this->obj['helper']->__invoke('partialLoopChildObject.phtml', $this->obj['data']);
	}
} else {
	echo $this->obj->message;
	$this->obj->helper->setObjectKey($this->vars()->obj->objectKey);
	echo $this->obj->helper->__invoke('partialLoopChildObject.phtml', $obj->data); 
}
