<?php
namespace Zend\Db\TableGateway;

use Zend\Db\TableGateway\StaticAdapterTableGateway;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-03-01 at 23:20:11.
 */
class StaticAdapterTableGatewayTest extends \PHPUnit_Framework_TestCase
{
    protected $mockAdapter = null;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->mockAdapter = $this->getMock('Zend\Db\Adapter\Adapter', null, array($this->getMock('Zend\Db\Adapter\Driver\DriverInterface')));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zend\Db\TableGateway\StaticAdapterTableGateway::setStaticAdapter
     */
    public function testSetStaticAdapter()
    {
        StaticAdapterTableGateway::setStaticAdapter($this->mockAdapter);
        $this->assertSame($this->mockAdapter, StaticAdapterTableGateway::getStaticAdapter());

        $adapter = new StaticAdapterTableGateway('foo');
        $this->assertSame($this->mockAdapter, $adapter->getAdapter());
    }

    /**
     * @covers Zend\Db\TableGateway\StaticAdapterTableGateway::getStaticAdapter
     */
    public function testGetStaticAdapter()
    {
        StaticAdapterTableGateway::setStaticAdapter($this->mockAdapter);
        $this->assertSame($this->mockAdapter, StaticAdapterTableGateway::getStaticAdapter());
    }
}
