<html>
<head>
	<title>Zend_Wildfire Demos and Tests</title>
	<style>
		BODY, TD {
			font-family:verdana,arial,helvetica,sans-serif;
			font-size:11px;		
		}
	</style>
</head>
<body>

<table border="0" width="100%" height="100%" cellpadding="10" cellspacing="0">
	<tr>
		<td valign="top" nowrap>
			<p><b>Zend_Log_Writer_Firebug</b></p>
			<ul>
				<li><a href="Zend-Log-Writer-Firebug/TestLogging" target="main">Test Logging</a></li>
				<li><a href="Zend-Log-Writer-Firebug/TestErrorController" target="main">Test Error Controller</a></li>
				<li><a href="Zend-Log-Writer-Firebug/TestLargeMessage" target="main">Test Large Message</a></li>
				<li><a href="Boot/Zend-Log-Writer-Firebug/TestDocExample.php?Example=WithController" target="main">Test Doc Example (With Controller)</a></li>
				<li><a href="Boot/Zend-Log-Writer-Firebug/TestDocExample.php?Example=WithoutController" target="main">Test Doc Example (Without Controller)</a></li>
			</ul>
			<p><b>Zend_Db_Profiler_Firebug</b></p>
			<ul>
				<li><a href="Zend-Db-Profiler-Firebug/TestLogging" target="main">Test Logging</a></li>
				<li><a href="Zend-Db-Profiler-Firebug/TestMultipleDatabases" target="main">Test Multiple Databases</a></li>
				<li><a href="Boot/Zend-Db-Profiler-Firebug/TestDocExample.php?Example=WithController" target="main">Test Doc Example (With Controller)</a></li>
				<li><a href="Boot/Zend-Db-Profiler-Firebug/TestDocExample.php?Example=WithoutController" target="main">Test Doc Example (Without Controller)</a></li>
			</ul>
			<p><b>Zend_Wildfire_Plugin_FirePhp</b></p>
			<ul>
				<li><a href="Zend-Wildfire-Plugin-Firephp/TestGroups" target="main">Test Groups</a></li>
			</ul>
			
			<br/>
			<br/>
			
			<p><b>Requirements</b></p>
			<ul>
				<li><a target="_blank" href="http://www.getfirefox.com/">Firefox 3</a></li>
				<li><a target="_blank" href="https://addons.mozilla.org/en-US/firefox/addon/1843">Firebug Extension</a></li>
				<li><a target="_blank" href="https://addons.mozilla.org/en-US/firefox/addon/6149">FirePHP Extension</a></li>
			</ul>

			<p><b>Instructions</b></p>
			<p>Click on the links above and<br>look for output in the Firebug Console.</p>
			
		</td>
		<td valign="top" width="100%">
			<iframe name="main" width="100%" height="100%" border="1"></iframe>
		</td>
	</tr>
</table>

</body>
</html>