<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Zend OpenID Server Example</title>
<style>
input.openid_login {
    background: url(login-bg.gif) no-repeat;
    background-color: #fff;
    background-position: 0 50%;
    color: #000;
    padding-left: 18px;
    width: 220px;
    margin-right: 10px;
}
input.openid_password {
    background-color: #fff;
    color: #000;
    padding-left: 18px;
    width: 220px;
    margin-right: 10px;
}
</style>
<script language="JavaScript">
function init() {
<?php
    if (isset($this->error)) {
        echo '    alert("' . $this->error . '");' . "\n";
    }
?>
    if (document.forms['register'].elements['openid_name'].value == '') {
        document.forms['register'].elements['openid_name'].focus();
    } else {
        document.forms['register'].elements['openid_password'].focus();
    }
}
</script>
</head>
<body onLoad="init()">
<?php
if (isset($this->error)) {
    echo '<noscript><div><b><font color="#ff0000">Error: ' . $this->error . '</font></b></div></noscript>';
}
?>
<div>
<form name="register" action="<?php $_SERVER['PHP_SELF']; ?>"
    method="post" onsubmit="this.login.disabled=true;">
<fieldset id="openid">
<legend>Register OpenID Account</legend>
<input type="hidden" name="openid_action" value="register">
<table border="0"><tr><td>
<label>Name:</label>
</td><td>
<input type="text" name="openid_name" <?php if (isset($this->name)) {echo ' value="' . $this->name . '"';} ?>>
</td></tr><tr><td>
<label>Password:</label>
</td><td>
<input type="password" name="openid_password">
</td></tr><tr><td>
<label>Re-type:</label>
</td><td>
<input type="password" name="openid_password2">
</td><td></tr><tr><td>&nbsp;</td><td>
<input type="submit" name="login" value="login">
</td></tr></table>
</fieldset>
</form>
</div>
</body>
</html>
