<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Zend OpenID Server Example</title>
</head>
<body>
<p>Than you for registration!</p>
<p>Your OpenID identity <b><a href="<?php echo $this->url;?>"><?php echo $this->url;?></a></b></p>
<p>You also can use OpenID 2.0 identity <b><a href="<?php echo $this->url2;?>"><?php echo $this->url2;?></a></b></p>
</body>
</html>