<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Zend OpenID Server Example</title>
</head>
<body>
<p>A site identifying as <a href="<?php echo $this->site;?>"><?php echo $this->site;?></a> has asked us for confirmation that <a href="<?php echo $this->url;?>"><?php echo $this->url;?></a> is your identity URL.</p>
<form name="trust" action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post">
<?php echo $this->sreg;?>
<input type="checkbox" name="forever">
<label for="forever">forever</label><br>
<input type="hidden" name="openid_action" value="trust">
<br>
<input type="submit" name="allow" value="Allow">
<input type="submit" name="deny" value="Deny">
</form>
</body>
</html>
